Repository Netflix/hollow, pull requests merged in 2019-03, with the labels that each got.

#407 Upgrade to gradle 5.1
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
  hollow-diff-ui/build.gradle
  hollow-explorer-ui/build.gradle
  hollow-jsonadapter/build.gradle
  hollow-test/build.gradle
  hollow-ui-tools/build.gradle
  hollow-zenoadapter/build.gradle
  hollow/build.gradle
Labels: enhancement

#402 Name all threads started by Hollow
  hollow-jsonadapter/src/main/java/com/netflix/hollow/jsonadapter/AbstractHollowJsonAdaptorTask.java
  hollow-jsonadapter/src/test/java/com/netflix/hollow/jsonadapter/chunker/JsonArrayChunkerTest.java
  hollow-perf/src/jmh/java/com/netflix/hollow/core/read/ReadWriteStateEngineTest.java
  hollow-ui-tools/src/main/java/com/netflix/hollow/ui/HollowUISession.java
  hollow-zenoadapter/src/main/java/com/netflix/hollow/zenoadapter/util/HollowStateEngineCreator.java
  hollow/src/main/java/com/netflix/hollow/api/client/HollowAnnouncementWatcher.java
  hollow/src/main/java/com/netflix/hollow/api/client/StaleHollowReferenceDetector.java
  hollow/src/main/java/com/netflix/hollow/api/consumer/HollowConsumer.java
  hollow/src/main/java/com/netflix/hollow/api/consumer/fs/HollowFilesystemAnnouncementWatcher.java
  hollow/src/main/java/com/netflix/hollow/api/producer/HollowIncrementalCyclePopulator.java
  hollow/src/main/java/com/netflix/hollow/api/producer/HollowIncrementalProducer.java
  hollow/src/main/java/com/netflix/hollow/api/sampling/TimeSliceSamplingDirector.java
  hollow/src/main/java/com/netflix/hollow/core/util/HollowWriteStateCreator.java
  hollow/src/main/java/com/netflix/hollow/core/util/SimultaneousExecutor.java
  hollow/src/main/java/com/netflix/hollow/core/util/Threads.java
  hollow/src/main/java/com/netflix/hollow/core/write/HollowBlobWriter.java
  hollow/src/main/java/com/netflix/hollow/core/write/HollowWriteStateEngine.java
  hollow/src/main/java/com/netflix/hollow/tools/checksum/HollowChecksum.java
  hollow/src/main/java/com/netflix/hollow/tools/combine/HollowCombiner.java
  hollow/src/main/java/com/netflix/hollow/tools/diff/HollowDiff.java
  hollow/src/main/java/com/netflix/hollow/tools/diff/HollowTypeDiff.java
  hollow/src/main/java/com/netflix/hollow/tools/diff/exact/mapper/DiffEqualityTypeMapper.java
  hollow/src/main/java/com/netflix/hollow/tools/diff/specific/HollowSpecificDiff.java
  hollow/src/main/java/com/netflix/hollow/tools/history/HollowHistoricalStateCreator.java
  hollow/src/main/java/com/netflix/hollow/tools/history/HollowHistory.java
  hollow/src/main/java/com/netflix/hollow/tools/history/keyindex/HollowHistoryKeyIndex.java
  hollow/src/main/java/com/netflix/hollow/tools/patch/delta/HollowStateDeltaPatcher.java
  hollow/src/main/java/com/netflix/hollow/tools/split/HollowSplitter.java
  hollow/src/test/java/com/netflix/hollow/core/index/SparseBitSetTest.java
  hollow/src/test/java/com/netflix/hollow/core/util/SimultaneousExecutorTest.java
  hollow/src/test/java/com/netflix/hollow/core/util/ThreadsTest.java
Labels: enhancement

#405 Check ordinal and byte data size limits.
  hollow/src/main/java/com/netflix/hollow/core/memory/ByteArrayOrdinalMap.java
Labels: bug

#410 Support HollowObjectHashCodeFinder for legacy cases.
  hollow/src/main/java/com/netflix/hollow/api/producer/HollowProducer.java
  hollow/src/test/java/com/netflix/hollow/api/producer/HashCodeFinderTest.java
Labels: enhancement

#409 Optimization for one input. Fix bugs for ignored types.
  hollow/src/main/java/com/netflix/hollow/tools/combine/HollowCombiner.java
  hollow/src/test/java/com/netflix/hollow/tools/combine/HollowCombinerIgnoreTest.java
Labels: bug, performance

#411 Events for blob stage and async blob publish
  hollow/src/main/java/com/netflix/hollow/api/metrics/HollowProducerMetrics.java
  hollow/src/main/java/com/netflix/hollow/api/producer/HollowProducer.java
  hollow/src/main/java/com/netflix/hollow/api/producer/ListenerSupport.java
  hollow/src/main/java/com/netflix/hollow/api/producer/listener/PublishListener.java
  hollow/src/test/java/com/netflix/hollow/api/producer/HollowProducerListenerTest.java
Labels: enhancement

#412 Vetoable listener support.
  hollow/src/main/java/com/netflix/hollow/api/producer/HollowProducer.java
  hollow/src/main/java/com/netflix/hollow/api/producer/ListenerSupport.java
  hollow/src/main/java/com/netflix/hollow/api/producer/listener/VetoableListener.java
  hollow/src/test/java/com/netflix/hollow/api/producer/HollowProducerListenerTest.java
Labels: enhancement

#413 Deprecate method that does unexpected things and document alternative
  hollow/src/main/java/com/netflix/hollow/core/schema/HollowObjectSchema.java
Labels: enhancement
